/** Palette generated by Material Palette - materialpalette.com/blue-grey/teal */

import { createGlobalStyle } from "styled-components";

/** Color names generated by https://chir.ag/projects/name-that-color */
const fiord = "#455A64";
const lynch = "#607D8B";
const geyser = "#CFD8DC";
const white = "#FFFFFF";
const persianGreen = "#009688";
const mainShaft = "#212121";
const boulder = "#757575";
const silver = "#BDBDBD";

const baseTheme = {
    background: {
        darkPrimary: fiord,
        primary: lynch,
        lightPrimary: geyser,
        accent: persianGreen,
    },
    
    color: {
        textOnPrimaryBg: white,
        primaryText: mainShaft,
        secondaryText: boulder,
    },
    
    border: {
        divider: silver
    }
}

const STYLED_COMPONENTS_THEME = {
    baseTheme,
    shadow: {
        base: "0px 0px 5px 0px rgba(0, 0, 0, 0.5)"
    },
    radius: {
        base: 5,
    },
    padding: {
        base: 10,
    },
    form: {
        input: {
            height: 40,
            width: 200,
            borderRadius: 5,
            fontSize: 12,
            lineHeight: 24,
            padding: 5,
        }
    },
    fontSize: {
        label: {
            fontSize: 12,
            lineHeight: 24,
        }, 
        tileTitle: {
            fontSize: 14,
            lineHeight: 28,
        }
    }
}

export default STYLED_COMPONENTS_THEME;

export const GlobalStyle = createGlobalStyle`
    * {
        box-sizing: border-box;
    }

    ul, li {
        display: block;
        list-style: none;
        padding: 0;
        margin: 0;
    }
`