const SCROLLBAR_WIDTH_PX = 20;
const TRANSITION_TIME_BASE = 150;
const TRANSITION_STYLE_BASE = `${TRANSITION_TIME_BASE}ms ease-out`;
// eslint-disable-next-line no-magic-numbers
const ANIMATION_FRAME_DURATION = 1000/60;

export {
    SCROLLBAR_WIDTH_PX,
    TRANSITION_STYLE_BASE,
    ANIMATION_FRAME_DURATION,
    TRANSITION_TIME_BASE
}